data:
  train_data_path: "/mnt/data-tmp/ghazal/DARai_DATA/timeseries_data/EMG_Modality_Top/hand_Both/IMU_Both/train"
  val_data_path: "/mnt/data-tmp/ghazal/DARai_DATA/timeseries_data/EMG_Modality_Top/hand_Both/IMU_Both/validation"
  test_data_path: "/mnt/data-tmp/ghazal/DARai_DATA/timeseries_data/EMG_Modality_Top/hand_Both/IMU_Both/test"
  sampling_rate: 12
  sequence_length: 10
  segments: 20
  batch_size: 8

model:
  name: "Transformer"
  dimensions: 9
  num_layers: 3
  output_base: "/home/ghazal/Activity_Recognition_benchmarking/timeseries_unimodal/"
  output_name: "IMU_all_30_ep"
  num_epochs: 60
  learning_rate: 0.0001
  save_best_only: true

output:
  plot_filename: "IMU_train_label_distribution"
